name: builder

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: install upx
        run: sudo apt install upx -y

      - name: build elf
        run: mkdir pkg;cd builders;chmod +x ./*.sh;./build-all.sh

      - name: build rpm
        run: ls ./pkg

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.version.outputs.value}}
          files: |
            pkg/rsm-linux-amd64
            pkg/rsm-linux-arm64
            pkg/rsm-mac-amd64
            pkg/rsm-win-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
